### PR TITLE
Add support for OpenAPI 3.1

### PR DESCRIPTION
**Pull request by easyt**
This pull request includes updates to the `Redocly OpenAPI Lint Action` to support OpenAPI 3.1 and adds a new test case for this version. Additionally, it introduces a sample OpenAPI 3.1 document for testing purposes.

### CODE REVIEW

**Review by bearcherian — APPROVED** [review]

**Comment by shiftkey** [comment]
As I understand it, https://github.com/easyt/redocly-cli-lint-action/blob/bb4337c89d05fd6f9ad6693a4a83dc784520e139/package.json#L29 will upgrade this action to `1.22.1`. The OpenAPI linter we are still on for internal use is stuck at `^1.0.0-beta.110`, and even getting to `1.0.0` caused me to trip https://github.com/Redocly/redocly-cli/issues/925 which is still a blocker.

I fear merging this in it's current form will start reporting false positives that we can't easily resolve, and that we should be in sync with `openapi-linter`.

**Review by mattpage — APPROVED** [review]
👍

**Comment by easyt** [comment]
I've updated the `redocly` dependencies to `1.0.0-beta.110`. Please re-review.

**Review by shiftkey — APPROVED** [review]

**Review by bearcherian — COMMENTED** [review]
~~Should there be an update to the version in `package.json`?~~ nvm, UI limits weren't showing the file

**Review by mattpage — APPROVED** [review]

**Pull request merged**
